project_id = "livbbxegwifbhtboyczy"

[functions.extension-status]
verify_jwt = false

[functions.heartbeat]
verify_jwt = false

[functions.check-inactive]
verify_jwt = false

[functions.brands]
verify_jwt = false

[functions.extension-download]
verify_jwt = false

[functions.azure-auth-init]
verify_jwt = false

[functions.azure-auth-callback]
verify_jwt = false
